"""empty message

Revision ID: 0bea85269324
Revises: be83b76aa4e0
Create Date: 2024-07-30 00:06:53.000326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bea85269324'
down_revision = 'be83b76aa4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.drop_column('favorites')

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.drop_column('favorites')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
