"""empty message

Revision ID: ac3f7bd24e4f
Revises: de30c63fd235
Create Date: 2024-07-31 22:48:37.036138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3f7bd24e4f'
down_revision = 'de30c63fd235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.drop_column('race')
        batch_op.drop_column('age')
        batch_op.drop_column('weight')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('age', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('race', sa.VARCHAR(length=250), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
