"""empty message

Revision ID: de30c63fd235
Revises: 8c9dbf425cc0
Create Date: 2024-07-31 22:08:51.035715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de30c63fd235'
down_revision = '8c9dbf425cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('race', sa.String(length=250), nullable=True))
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=True))

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('user_name')

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('Characters', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.drop_column('race')
        batch_op.drop_column('age')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
